[package]
name = "simple_actix_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
derive-new = "0.5.9"
futures = "0.3.28"
tokio = "1.27.0"
